include theos/makefiles/common.mk

BUNDLE_NAME = EdgeAlertSettings
EdgeAlertSettings_FILES = /mnt/d/codes/edgealert/edgealertsettings/EdgeAlertSettingsController.mm
EdgeAlertSettings_INSTALL_PATH = /Library/PreferenceBundles
EdgeAlertSettings_FRAMEWORKS = UIKit QuartzCore CoreGraphics MessageUI Social Twitter
EdgeAlertSettings_PRIVATE_FRAMEWORKS = Preferences
EdgeAlertSettings_CFLAGS = -fobjc-arc
EdgeAlertSettings_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/bundle.mk

all::
